### ISSUE TITLE
Problems while "Checking if Icinga is currently dumping config..."

### ISSUE THREAD

**Issue by PinkFrog** [lazyfrosch/icinga2-scom-connector#7]
Hi, 

I can not run scom_connector monitor because I got every time the notice "UNKNOWN - Icinga is currently reloading data into IDO. We can not work at that point!". 

I've checked the script, but I have no idea to debug this. Can you help me? 

Thank you!

**Comment by PinkFrog** [comment]
Seems to be a change in teh database schema in SCOM 2016, it works after changing lines 236-239 a little bit: 

`236 SELECT count(*) FROM icinga_programstatus
237 WHERE config_dump_in_progress > 0";
238 #  OR program_end_time > 1
239 #";`

**Comment by swizzly** [comment]
I had the same Problem, your hint helped! Thanks!
But without checking the program_end_time aren't we missing something important?
